-- Generated by image sourcing research script.
-- Review before running. Only rows with a confident match are included.

-- 가톨릭 목포 성지 (광주) [tourapi, TourAPI(public)]
UPDATE holy_sites SET image_url = 'https://tong.visitkorea.or.kr/cms/resource/49/4054849_image2_1.jpg' WHERE id = 'a9d7452a-a271-4634-bbed-42e977532c69';

-- 가실성당 (대구) [tourapi, TourAPI(public)]
UPDATE holy_sites SET image_url = 'https://tong.visitkorea.or.kr/cms/resource/04/3490504_image2_1.jpg' WHERE id = 'ed60c7d6-ee9f-4cd1-a5ff-28730e0dc42c';

-- 한티 순교성지 (대구) [tourapi, TourAPI(public)]
UPDATE holy_sites SET image_url = 'https://tong.visitkorea.or.kr/cms/resource/20/3490520_image2_1.jpg' WHERE id = '3c5c55a8-c994-4d95-882c-19ab96beb26c';

-- 솔뫼성지 (대전) [tourapi, TourAPI(public)]
UPDATE holy_sites SET image_url = 'http://tong.visitkorea.or.kr/cms/resource/84/3535184_image2_1.jpg' WHERE id = '7e9b0733-1c97-4d1c-beb0-fd7e9c6ab8c0';

-- 신리성지 (대전) [tourapi, TourAPI(public)]
UPDATE holy_sites SET image_url = 'https://tong.visitkorea.or.kr/cms/resource/61/4064461_image2_1.jpg' WHERE id = '33e0cfff-5e24-44cd-980f-a69bfe09d4ff';

-- 여사울성지 (대전) [tourapi, TourAPI(public)]
UPDATE holy_sites SET image_url = 'http://tong.visitkorea.or.kr/cms/resource/39/3560639_image2_1.jpg' WHERE id = '4881746c-8074-4912-9420-4d211491bd58';

-- 울산 죽림굴(대왕암) 순교지 (부산) [tourapi, TourAPI(public)]
UPDATE holy_sites SET image_url = 'http://tong.visitkorea.or.kr/cms/resource/16/3583516_image2_1.jpg' WHERE id = '83fa7ec0-8694-4a20-9dd9-31c19020bbcb';

-- 당고개순교성지 (서울) [tourapi, TourAPI(public)]
UPDATE holy_sites SET image_url = 'http://tong.visitkorea.or.kr/cms/resource/19/3568219_image2_1.jpg' WHERE id = 'ba46ee91-7cc8-4517-a079-04ad83235365';

-- 절두산 순교성지 (서울) [tourapi, TourAPI(public)]
UPDATE holy_sites SET image_url = 'http://tong.visitkorea.or.kr/cms/resource/76/3571776_image2_1.jpg' WHERE id = '3f20f0d4-e2df-4b33-9d9c-a8c77ac679cd';

-- 단내 성가정 성지 (수원) [tourapi, TourAPI(public)]
UPDATE holy_sites SET image_url = 'http://tong.visitkorea.or.kr/cms/resource/01/3541501_image2_1.jpg' WHERE id = 'dc218e5a-3218-4364-bc6d-4c5737122d53';

